- name: Install bind9
  ansible.builtin.apt:
    name: bind9
    state: present

- name: Definir nossas zonas DNS
  ansible.builtin.blockinfile:
    path: /etc/bind/named.conf.local
    block: |
      zone "proccm.redealuno.usp.br" {
        type master;
        notify no;
        file "/etc/bind/db.proccm.redealuno.usp.br";
      };

      zone "0.168.192.in-addr.arpa" {
        type master;
        notify no;
        file "/etc/bind/db.192.168.0";
      };
  notify: restartar bind

- name: Configurar o servidor DNS
  ansible.builtin.copy:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: '0644'
  notify: restartar bind


- name: Gerar entradas para os bancos de dados DNS e DNS reverso
  ansible.builtin.template:
    src: "templates/{{ item.dns }}.j2"
    dest: "{{ item.path }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - { dns: "dns", path: "/etc/bind/db.proccm.redealuno.usp.br"}
    - { dns: "dns_reverso", path: "/etc/bind/db.192.168.0"}
  notify: restartar bind

- name: Enable bind9
  ansible.builtin.service:
    name: bind9
    state: started 
    enabled: true





- handler:
  - name: restartar bind
    ansible.builtin.service:
      name: bind9
      state: restarted 
