
- name: Install LDAP
  ansible.builtin.apt:
    state: present
    name:
      - slapd
      - ldap-utils
      - ldapscripts
      - libpam-cracklib
      - gnutls-bin
      - ssl-cert
      - libnss-ldapd

# https://wiki.zimbra.com/wiki/OpenLDAP_MDB_vs_HDB_performance