- name: Install CUPS e sane (scanner)
  community.general.pacman:
    update_cache: true
    state: present
    name:
      - cups
      - libcups
      - sane

- name: Start e enable service cups.service
  ansible.builtin.service:
    name: cups.service
    state: started
    enabled: true

- name: Install driver da impressora
  kewlfft.aur.aur:
    update_cache: true
    state: present
    use: yay
    name:
      - samsung-unified-driver

## wiki tem mais umas websteps pra impressora,
## n sei se faz sentido add aqui de alguma forma

# Parametrizar ese IP?
- name: Fazer impressora acessivel pela rede
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sane.d/xerox_mfp.conf
    regexp: "^tcp 143.107.90.4"
    line: "tcp 143.107.90.4"
    state: present
