- name: Install CUPS e sane (scanner)
  community.general.pacman:
    update_cache: true
    state: present
    name:
      - cups
      - libcups
      - sane

# acho q preciso add o become true e aurbuilder user
- name: Install driver da impressora
  kewlfft.aur.aur:
    update_cache: true
    state: present
    use: yay
    name:
      - samsung-unified-driver

- name: Start e enable service cups.service
  ansible.builtin.service:
    name: cups.service
    state: started
    enabled: true

## wiki tem mais umas websteps pra impressora,
## n sei se faz sentido add aqui de alguma forma
- name: Fazer impressora acessivel pela rede
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sane.d/xerox_mfp.conf
    regexp: "^tcp {{ impressora_ip }}"
    line: "tcp {{ impressora_ip }}"
    state: present
