- name: Fresh client install
- hosts: localhost
  pre_tasks:
    # Estou assumindo q ele cria dirs intermediarios
    - name: Mkdirs no mnt pra dar mount
      ansible.builtin.file:
        path: /mnt/archinstall/scratch
        state: directory
        mode: "0755"

    # N sei se formatar sda2 eh necessario
    # N formatar sda3 pq queremos manter scratch
    - name: Format /dev/sda1 & /dev/sda2
      become: true
      community.general.filesystem:
        fstype: "{{ item.fstype }}"
        dev: "{{ item.dev }}"
        loop:
          - { fstype: "ext4", dev: "/dev/sda1" }
          - { fstype: "swap", dev: "/dev/sda2" }

      # todo: add explicacao do pq isso funciona
    - name: Mount sda1 (/) in /mnt/archinstall and sda3 (/scratch) in /mnt/archinstall/scratch
      ansible.posix.mount:
        path: /mnt/archinstall
        src: /dev/sda1
        fstype: ext4
        state: mounted
        loop:
          - { path: "/mnt/archinstall", src: "/dev/sda1" }
          - { path: "/mnt/archinstall/scratch", src: "/dev/sda3" }

  tasks:
    - name: Install archinstall
      become: true
      community.general.pacman:
        name: archinstall
        state: present

    - name: Run archinstall with our client settings
      become: true
      changed_when: true
      ansible.builtin.command: "archinstall --config {{ url_config }} --creds {{ credentials }} --silent"
      vars:
        url: "<url_aqui>"
        credetentials: "<algo_aqui>"
        # TODO: provavelmente transformar nisso num jinja template + logica pra inferir hostname ou proomptar o user se nao descobrir
