- name: Instalar pacotes relacionados ao LDAP
  become: true
  community.general.pacman:
    state: present
    name:
      - openldap

# URI (Uniform resource information): define endereco na base de dados do ldap;
# BASE é o ponto partida de buscas dentro do ldap, "default  base  DN  to  use  when  performing  ldap operations.";
# TLS_CACERT: o certificado ssl que vc vai usar pra conectar com o servidor de forma a garantir que o tráfego é encriptado e seguro;
# docs: https://www.openldap.org/software//man.cgi?query=ldap.conf&sektion=5&apropos=0&manpath=OpenLDAP+2.4-Release
- name: Configurar cliente LDAP
  ansible.builtin.copy:
    dest: /etc/openldap/ldap.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      BASE            dc=proccm,dc=redealuno,dc=usp,dc=br
      URI             ldap://proccm.redealuno.usp.br:{{<porta_ldap>}}

      TLS_CACERT /etc/ssl/certs/ca.cert
