---
# tasks file for archinstall

- name: Instalar deps
  become: true
  ansible.builtin.package:
    state: present
    name: 
      - pkgconf
      - "python{{ versao }}-virtualenv" # apt packages poem um 3 na frente de python, sabe se la pq quando 2.7 ta deprecado fazem anos 
      - "python{{ versao }}-setuptools"
      - "python{{ versao }}-pip"

- name: Clonar archinstall na versao q queremos
  become: true
  ansible.builtin.git:
    repo: 'https://github.com/archlinux/archinstall.git'
    dest: "{{ archinstall_path }}"
    version: 'f16af43949085b06478d2e4c45ed61fa8e595171' # Commit logo dps de darem merge no fix pra pre-mounted diskconfig (commit 30a374a do PR#2221)
    # https://github.com/archlinux/archinstall/tree/f16af43949085b06478d2e4c45ed61fa8e595171

# todo: checar se isso instala soh o q ta no repo ou vai dar um pull e zuar a versao
- name: Instalar archinstall a partir do repo clonado
  become: true
  ansible.builtin.pip:
    name: "git+file://{{ archinstall_path }}"
    virtualenv: "{{ venv_path }}"

  # input_name e input_numeral devem ser passados pela CLI com a flag -e, --extra-vars "input_name=DrAbobrinha input_numeral=42"
  # Caso nome inserido ja exista, atualiza mac address dele no inventorio (aka pc quebrou tamo trocando por outro e reaproveitando o hostname)
  # TODO: isso atualiza soh pra run ou vai ser escrto pra arquivo?
- name: Checa se eh um pc novo (novo mac address)
  when: mac not in mac2hostname
  ansible.builtin.add_host:
    name: "{{ input_name | mandatory }}"
    groups: "clientes"
    ansible_host: "192.168.0.{{ input_numeral | mandatory }}"
    mac_ethernet: "{{ mac }}"
    # todo: spawnar task or something pra atualizar o hosts do proccm pq se n resto vai dar pau
  # notify: proccm update hosts  # = proccm_hosts no proccm, delegate?


- name: Configurar archinstall file com nosso hostname
  ansible.builtin.template:
    src: templates/configuration.j2
    dest: /tmp/configuration.json
    mode: "0777"

- name: Copiar credentials
  ansible.builtin.copy:
    src: files/credentials.json
    dest: /tmp/credentials.json
    mode: "0777"

- name: Run archinstall with our client settings
  become: true
  changed_when: true
  ansible.builtin.command: "{{ venv_path }}/bin/archinstall --config {{ config_path }} --creds {{ credentials }} --silent"
  vars:
    config_path: "/tmp/configuration.json"
    credentials: "/tmp/credentials.json"
