---
# tasks file for archinstall

- name: Instalar deps
  become: true
  ansible.builtin.package:
    state: present
    name: 
      - pkgconf
      - arch-install-scripts # archinstall depende do pacstrap
      - python-pip

- name: Instalar archinstall
  become: true
  ansible.builtin.pip:
    state: present
    name: archinstall
    version: "2.7.1"
    extra_args: --break-system-packages

- name: Setar tempo ntp coisas TODO
  become: true
  ansible.builtin.service:
    name: "systemd-timesyncd.service"
    state: started


  # input_name e input_numeral devem ser passados pela CLI com a flag -e, --extra-vars "input_name=DrAbobrinha input_numeral=42"
  # Caso nome inserido ja exista, atualiza mac address dele no inventorio (aka pc quebrou tamo trocando por outro e reaproveitando o hostname)
  # TODO: isso atualiza soh pra run ou vai ser escrto pra arquivo?
- name: Checa se eh um pc novo (novo mac address)
  when: mac not in mac2hostname
  ansible.builtin.add_host:
    name: "{{ input_name | mandatory }}"
    groups: "clientes"
    ansible_host: "192.168.0.{{ input_numeral | mandatory }}"
    mac_ethernet: "{{ mac }}"
    # todo: spawnar task or something pra atualizar o hosts do proccm pq se n resto vai dar pau
  # notify: proccm update hosts  # = proccm_hosts no proccm, delegate?


- name: Configurar archinstall file com nosso hostname
  ansible.builtin.template:
    src: templates/configuration.j2
    dest: /tmp/configuration.json
    mode: "0777"

- name: Copiar credentials
  ansible.builtin.copy:
    src: files/credentials.json
    dest: /tmp/credentials.json
    mode: "0777"

- name: Run archinstall with our client settings
  become: true
  changed_when: true
  ansible.builtin.command: "archinstall --config {{ config_path }} --creds {{ credentials }} --silent"
  vars:
    config_path: "/tmp/configuration.json"
    credentials: "/tmp/credentials.json"
