## Configuração do NFS

# Instalação e inicialização dos serviços
- name: install nfs-utils
  community.general.pacman:
    name: nfs-utils

- name: enable and start relevant NFS services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - 'rpcbind.service'
    - 'nfs-client.target'
    - 'remote-fs.target'

# Garantimos que os serviços só iniciarão depois que for feita a conexão com o proccm
- name: enable wait-online service
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
    - systemd-networkd.service
    - systemd-networkd-wait-online.service


- name: replace service files
  copy:
    src: "files/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - 'nfs-client.target'
    - 'rpcbind.service'

- name: make systemd reread configs
  systemd:
    daemon_reload: yes

# Modificar o bashrc para incluir o mountpoint NFS /scripts no PATH

- name: replace bashrc
  copy:
    src: files/bash.bashrc
    dest: /etc/bash.bashrc
    owner: root
    group: root
    mode: 0644

## Configuração do LDAP
## Pulei passos envolvendo a porta até ter certeza que é safe ter isso público.

# Instalação do openldap
- name: install openldap
  community.general.pacman:
    name: openldap

# Transferência do certificado 
- name: copy certificate
  copy:
    src: /etc/ssl/certs/cacert.pem
    dest: /etc/ssl/certs/ca.cert
    owner: root
    group: root
    mode: 0644

# Modificação do ldap.conf (TBD)

# Instalação do ldap para o pam
- name: install nss-pam-ldapd
  community.general.pacman:
    name: nss-pam-ldapd

# Modificar o nsswitch.conf para incluir o ldap
- name: replace nsswitch.conf
  copy:
    src: files/nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644

# Modificação do nslcd.conf (TBD)

# Inicialização do nslcd
- name: enable and start nslcd.service
  systemd:
    name: nslcd.service
    state: started
    enabled: yes

# Modificar os módulos do PAM para incluirem o LDAP.
- name: replace PAM modules
  copy:
    src: "files/{{ item }}"
    dest: "/etc/pam.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - 'system-auth'
    - 'su'
    - 'su-l'
    - 'passwd'

## Configuração da interface gráfica

# Instalação dos drivers de vídeo e do Xorg
- name: install video drivers and xorg
  community.general.pacman:
    name:
      - mesa
      - lib32-mesa
      - libva-intel-driver
      - xorg-server
      - xf86-video-intel

# Configuração do layout do teclado

