- name: mkdirs no mnt pra dar mount
  block:
    - name: mkdir /mnt/archinstall
      ansible.builtin.file:
        path: /mnt/archinstall
        state: directory
        mode: "0755"

    - name: mkdir /mnt/archinstall/scratch
      ansible.builtin.file:
        path: /mnt/archinstall/scratch
        state: directory
        mode: "0755"

- name: Format /dev/sda1
  become: true
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sda1

  ## N sei se essa etapa eh necessaria:
- name: Format /dev/sda2
  become: true
  community.general.filesystem:
    fstype: swap
    dev: /dev/sda2

# N formatar sda3 pq queremos manter scratch

- name: mount device sda (1 & 3)
  block:
    - name: Mount sda1 (/) in /mnt/archinstall
      ansible.posix.mount:
        path: /mnt/archinstall
        src: /dev/sda1
        fstype: ext4
        state: mounted

    - name: Mount sda3 (/) in /mnt/archinstall/scratch
      ansible.posix.mount:
        path: /mnt/archinstall/scratch
        src: /dev/sda3
        fstype: ext4
        state: mounted
