- name: Install archinstall
  become: true
  community.general.pacman:
    name: archinstall
    state: present

- name: Run archinstall with our client settings
  become: true
  changed_when: true
  ansible.builtin.command: "archinstall --config {{ url_config }} --creds {{ credentials }} --silent"
  vars:
    url: "<url_aqui>"
    credetentials: "<algo_aqui>"
