- name: Set authorized key for remote user
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.pub_key }}"
    loop:
      - { username: barzilay, pubkey: "" }
      # - { username: joel, pubkey: "" }
#   key:  https://github.com/charlie.keys
# ou algo meio
#   key: "{{ lookup('file', '/home/charlie/.ssh/id_rsa.pub') }}"
