- hosts: proccm
  tasks:
    - name: Transferir root public key do proccm pra o pc atual
      ansible.posix.synchronize:
        src: /root/.chave_publica_rsa_proccm
        dest: /root/.ssh/authorized_keys
        mode: pull
      delegate_to: localhost
# ref: https://stackoverflow.com/a/35742157
