- name: Configurar cliente DHCP
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/network/wired.network
    owner: root
    group: root
    mode: "0644"
    # Clientes normalmente soh tem uma interface de rede cabeada (mas alguns novos parecem poder vir com wifi tb),
    # ao ordenar as interfaces em ordem alfabetica, garantido por 'Predictable Network Interface Device Names',
    # sempre teremos as interfaces cabeadas primeiro (en, lo, wl e ww sao as unicas opcoes validas para comeco do nome).
    # refs:
    # https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-understanding_the_predictable_network_interface_device_names
    # https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
    content: |-
      [Match]
      Name={{ ansible_facts.interfaces.sort()[0] }}

      [Network]
      DHCP=ipv4

- name: Start & enable service systemd-networkd & systemd-resolved
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
    loop:
      - systemd-networkd
      - systemd-resolved

- name: Create a symbolic link
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
    force: true
