- name: Configurar pacman
  become: true
  block:
    - name: Add Color & VerbosePkgLists to pacman.conf
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        regexp: "^#?{{ item }}"
        line: "{{ item }}"
        state: present
        loop:
          - Color
          - VerbosePkgLists # organizes updated packages in tabular format which makes their list readable

    - name: Setar downloads paralelos (max 25)
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        regexp: "^#?ParallelDownloads"
        line: ParallelDownloads = 25
        state: present

    - name: Add ILoveCandy to pacman
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        regexp: "^ILoveCandy"
        insertafter: "^# Misc options"
        line: ILoveCandy
        state: present

- name: Configure yay
  become: true
  block:
    - name: Install yay
      community.general.pacman:
        name: yay
        state: present

    # Para: https://github.com/kewlfft/ansible-aur
    - name: Create the `aur_builder` user for ansible to use when installing something with yay
      ansible.builtin.user:
        name: aur_builder
        create_home: true
        group: wheel
