- name: Configurar pacman
  become: true
  block:
    - name: Add Color & VerbosePkgLists to pacman.conf
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        regexp: "^#?{{ item }}"
        line: "{{ item }}"
        state: present
        loop:
          - Color
          - VerbosePkgLists # organizes updated packages in tabular format which makes their list readable

    - name: Setar downloads paralelos (max 25)
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        regexp: "^#?ParallelDownloads"
        line: ParallelDownloads = 25
        state: present

    - name: Add ILoveCandy ao pacman ([-------------C o o o ])
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        regexp: "^ILoveCandy"
        insertafter: "^# Misc options"
        line: ILoveCandy
        state: present

- name: Configurar yay
  become: true
  block:
    - name: Instalar yay
      community.general.pacman:
        name: yay
        state: present

    # Para a collection q lida com yay: https://github.com/kewlfft/ansible-aur
    - name: Criar usuario `aur_builder` para o ansible usar quando instalar algo com o  yay
      ansible.builtin.user:
        name: aur_builder
        create_home: true
        group: wheel

    - name: Permitir que usuario `aur_builder` use `sudo pacman` sem senha
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        validate: /usr/sbin/visudo -cf %s
        mode: "0644"
        create: true
