- name: Install bind9
  ansible.builtin.apt:
    name: bind9
    state: present

- name: # todo
  ansible.builtin.blockinfile:
    path: /etc/bind/named.conf.local
    block: |
      zone "proccm.redealuno.usp.br" {
        type master;
        notify no;
        file "/etc/bind/db.proccm.redealuno.usp.br";
      };

      zone "0.168.192.in-addr.arpa" {
        type master;
        notify no;
        file "/etc/bind/db.192.168.0";
      };


  # todo:  named.conf.options


- name: Enable bind9
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
