---
# vars file for partition_mbr
swap_size: input_swap | default(6)
root_partition:    "{{ '1' if 'uefi' not in ansible_run_tags else '2' }}"
swap_partition:    "{{ '2' if 'uefi' not in ansible_run_tags else '3' }}"
scratch_partition: "{{ '3' if 'uefi' not in ansible_run_tags else '4' }}"

mbr_partitions:
  - { number: "1", fs: "ext4", part_start: "0%", part_end: "50GB" }
  - { number: "2", fs: "swap", part_start: "50GB", part_end: "{{ swap_size + 50 }}GB" }
  - { number: "3", fs: "ext4", part_start: "{{ swap_size + 50 }}GB", part_end: "100%" }


# gpt_partitions:
#   - { label: "gpt", flags: "", name: "", number: "1", fs: "fat32", part_start: "0%", part_end: "1GiB" }
#   - { label: "gpt", flags: "", name: "", number: "2", fs: "ext4", part_start: "1GiB", part_end: "51GB" }
#   - { label: "gpt", flags: "", name: "", number: "3", fs: "swap", part_start: "51GB", part_end: "{{ swap_size + 51 }}GB" }
#   - { label: "gpt", flags: "", name: "", number: "4", fs: "ext4", part_start: "{{ swap_size + 51 }}GB", part_end: "100%" }
