- name: Configurar /etc/hosts
  become: true
  block:
    - name: Add hosts gerais
      ansible.builtin.copy:
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"
        content: |-
          # The following lines are desirable for IPv6 capable hosts
          ::1             localhost ip6-localhost ip6-loopback
          ff02::1         ip6-allnodes
          ff02::2         ip6-allrouters

          # The following lines are desirable for IPv4 capable hosts
          127.0.0.1       localhost
          143.107.79.66   proccm
          143.107.90.10   fleming

    - name: Add hostname ao hosts
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        line: "{{ hostvars[hostname][ansible_host] }}  {{ hostname }}" # 192.168.0.X     nome_da_máquina
        state: present
