# TODO: ainda n sei como fazer pra o sistema inferir qual pc ele eh,
# n lembro se nome define ip ou ip define nome

# sepa quando o ansible roda do pendrive antes de tudo,
# checar ip e nome do pc e guardar como variavel pra dps

- name: Configurar /etc/hosts
  become: true
  block:
    - name: Add hosts gerais
      ansible.builtin.copy:
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"
        content: |-
          # The following lines are desirable for IPv6 capable hosts
          ::1             localhost ip6-localhost ip6-loopback
          ff02::1         ip6-allnodes
          ff02::2         ip6-allrouters

          # The following lines are desirable for IPv4 capable hosts
          127.0.0.1       localhost
          143.107.79.66   proccm
          143.107.90.10   fleming

      # todo, vars aqui :
    - name: Add hostname ao hosts
      ansible.builtin.lineinfile:
        path: /etc/pacman.conf
        line: "{{ hostvars[hostname][ansible_host] }}  {{ hostname }}" # 192.168.0.X     nome_da_máquina
        state: present

# todo, vars aqui :
# se descobrir essa info antes sepa da pra fazer o archinstall ja colocar o nome certo de cara
- name: Configurar hostname
  become: true
  ansible.builtin.copy:
    dest: /etc/hostname
    owner: root
    group: root
    mode: "0644"
    content: "{{ hostname }}"
