- name: Install arch
  hosts: localhost
  roles:
    - read_client_vars
    - partition
    - archinstall


# - hosts: proccm
#   vars:
#     root_path: groups["chroot_path"][0]
#   tasks:
#     - name: Copiar CA cert do proccm para o localhost
#       become: true
#       ansible.builtin.fetch:
#         src: /etc/ssl/certs/cacert.pem
#         dest: "{{ root_path }}/etc/ssl/certs/ca.cert"
#         flat: true


# rodar playbook com `sudo -E` pra preservar env pro chroot (?) #todo checar se eh necessario
# -E, --preserve-env:
# Indicates to the security policy that the user wishes to preserve their existing environment variables. 
# The security policy may return an error if the user does not have permission to preserve the environment.
- name: Config client
  hosts: chroot_path
  connection: community.general.chroot
  vars:
    porta_ldap: hostvars["proccm"].ldap_port
  roles:
    - pacman_conf
    - hosts
    - install_utilities
    - ip_fixo
    - nfs
    - ldap
    - pam
    - role: cups
      vars:
        impressora_ip: "143.107.90.4"
    - role: ssh_keys
      tags: cp_ssh_keys
